### PR TITLE
#108 Workaround for GROUP BY <integer>

### LINKED ISSUE #108: VS Workaround for `GROUP BY <integer>`
## Summary

When users combine integer constants as expressions with `DISTINCT`, the engine pushes down `GROUP BY <integer-constant>`. Exasol database interprets this as "group by column number", which yields wrong results. What should happen here is that you get a result with a single group. `GROUP BY TRUE`, `GROUP BY '0'` or any other non-integer constant will work as expected.

Note that some databases interpret this as "group by integer constant". So the behavior is database specific. The reason is that this case is *not covered by the SQL standard*.

Workaround:

The adapter should work around this by turning `GROUP BY <integer-constant>` into `GROUP BY <other-constant>`.

Theoretically that should be done on a db-by-db basis, but that is too much effort, so a general workaround in VSCL and VSCJ should be implemented. This can be overridden in the dialect if there is ever the need.

## Features

- Turns `GROUP BY <integer-constant>` into `GROUP BY <other-constant>`

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #108

### CODE REVIEW

File: src/test/java/com/exasol/adapter/dialects/exasol/AbstractExasolSqlDialectIT.java [hunk 1]
```diff
@@ -855,6 +858,42 @@ void testWildcards() throws SQLException {
                 table().row("A", "VARCHAR(20) UTF8", null, null, null).matches());
     }
 
+    @Test
+    @DisplayName("Verify that DISTINCT with integer literal works")
```
Comment (ckunki) [inline src/test/java/com/exasol/adapter/dialects/exasol/AbstractExasolSqlDialectIT.java:862]:
```suggestion
    @DisplayName("Verify DISTINCT with integer literal")
```

**Review by ckunki — CHANGES_REQUESTED** [review]

**Review by ckunki — APPROVED** [review]
