### PR TITLE
Bugs/6 exception with timestamps

### LINKED ISSUE #6: Throw an Exception if Exasol dialect uses Timestamp with local time zone
https://github.com/exasol/virtual-schema-common-java/issues/135

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #6

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitor.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
+package com.exasol.adapter.dialects.exasol;
+
+import static com.exasol.adapter.dialects.exasol.ExasolSqlDialect.EXASOL_TIMESTAMP_WITH_LOCAL_TIME_ZONE_SWITCH;
+
+import java.util.logging.Logger;
+
+import com.exasol.adapter.dialects.*;
+import com.exasol.adapter.sql.SqlLiteralTimestampUtc;
+
+public class ExasolSqlGenerationVisitor extends SqlGenerationVisitor {
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitor.java:10]: JavaDoc missing.

File: src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitor.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+            return super.visit(literal);
+        } else {
+            throw new UnsupportedOperationException(
+                    "Attention! Using literals and constant expressions with datatype `TIMESTAMP WITH LOCAL TIME ZONE` " +
+                            "in Virtual Schemas can produce an incorrect result. We suggest to use 'TIMESTAMP' instead. " +
+                            "If you take a risk and want to use `TIMESTAMP WITH LOCAL TIME ZONE` anyway, please, " +
+                            "create a Virtual Schema with an additional property " +
+                            "IGNORE_ERRORS = '" + EXASOL_TIMESTAMP_WITH_LOCAL_TIME_ZONE_SWITCH + "'. " +
+                            "We also recommend to set Exasol system `time_zone` " +
+                            "to UTC while working with `TIMESTAMP WITH LOCAL TIME ZONE`.");
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitor.java:38]:
```suggestion
                    "Attention! Using literals and constant expressions with datatype `TIMESTAMP WITH LOCAL TIME ZONE` " +
                            "in Virtual Schemas can produce an incorrect results. We recommend using 'TIMESTAMP' instead. " +
                            "If you are willing to take the risk and want to use `TIMESTAMP WITH LOCAL TIME ZONE` anyway, please, " +
                            "create a Virtual Schema with the following additional property " +
                            "IGNORE_ERRORS = '" + EXASOL_TIMESTAMP_WITH_LOCAL_TIME_ZONE_SWITCH + "'. " +
                            "We also recommend to set Exasol system `time_zone` " +
                            "to UTC while working with `TIMESTAMP WITH LOCAL TIME ZONE`.");
```

File: src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitor.java (hunk 1 above)
Comment (AnastasiiaSergienko) [reply src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitor.java:10]: added
