### PR TITLE
#69 Fix hashtype mapping

### LINKED ISSUE #69: Hashtype columns reported with wrong type
The virtual schema reports `HASHTYPE` columns as `CHAR(32) ASCII` when using `DESCRIBE`. These columns should be correctly reported as `HASHTYPE(16 BYTE)`.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #69

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/exasol/ExasolFromExaQueryRewriter.java [hunk 1]
```diff
@@ -24,11 +20,7 @@ public ExasolFromExaQueryRewriter(final SqlDialect dialect, final RemoteMetadata
     }
 
     @Override
-    protected String generateImportStatement(final String connectionDefinition, final String pushdownQuery)
-            throws SQLException {
-        final String importStatement = "IMPORT FROM EXA " + connectionDefinition + " STATEMENT '"
-                + pushdownQuery.replace("'", "''") + "'";
-        LOGGER.finer(() -> "IMPORT push-down statement:\n" + importStatement);
```
Comment (kaklakariada) [inline src/main/java/com/exasol/adapter/dialects/exasol/ExasolFromExaQueryRewriter.java:31]: Removed logger because super class already logs this.

File: src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectJdbcConnectionIT.java [hunk 2]
```diff
@@ -48,11 +48,4 @@ void testCharMappingAscii() {
     void testCastVarcharToChar() {
         castFrom("VARCHAR(20)").to("CHAR(40)").input("Hello.").verify(pad("Hello.", 40));
     }
-
-    @Test
-    void testDefaultHashType() {
-        typeAssertionFor("HASHTYPE").withValue("550e8400-e29b-11d4-a716-446655440000")
-                .expectDescribeType("CHAR(32) ASCII").expectTypeOf("HASHTYPE(16 BYTE)").expectResultSetType("CHAR")
-                .expectValue("550e8400e29b11d4a716446655440000").runAssert();
-    }
```
Comment (kaklakariada) [inline src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectJdbcConnectionIT.java:57]: Test moved to super class

File: src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectLocalConnectionIT.java [hunk 3]
```diff
@@ -82,11 +82,4 @@ void testGeometryMapping() {
     void testCastVarcharAsGeometry() {
         castFrom("VARCHAR(20)").to("GEOMETRY(5)").input("POINT(2 5)").verify("POINT (2 5)");
     }
-
-    @Test
-    void testDefaultHashType() {
-        typeAssertionFor("HASHTYPE").withValue("550e8400-e29b-11d4-a716-446655440000")
-                .expectDescribeType("CHAR(32) ASCII").expectTypeOf("HASHTYPE(16 BYTE)").expectResultSetType("HASHTYPE")
-                .expectValue("550e8400e29b11d4a716446655440000").runAssert();
-    }
```
Comment (kaklakariada) [inline src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectLocalConnectionIT.java:91]: Test moved to super class

**Review by jakobbraun — APPROVED** [review]
