### PR TITLE
Bug/92 schema name property

### LINKED ISSUE #92: Broken handling of tables when SCHEMA_NAME property is not set
Tested this using exasol-virtual-schema, but I assume this is a problem in the jdbc implementation already...

#### setup
```sql
create schema VSA;
CREATE JAVA ADAPTER SCRIPT VSA.EXASOL_ADAPTER AS
    %scriptclass com.exasol.adapter.RequestDispatcher;
    %jar /buckets/bfsdefault/default/virtual-schema-dist-10.1.0-exasol-7.0.2.jar;
/

create user BOB identified by "secret";
grant CREATE SESSION to BOB;

create or replace connection LOCAL_BOB
    to 'jdbc:exa:localhost/<fingerprint>:8563'
    user 'bob' identified by 'secret';

create schema s1;
    create table FOR_BOB(i int);
    grant select on for_bob to bob;

create schema s2;
    create table FOR_BOB(j int);
    grant select on for_bob to bob;

create virtual schema nomercy
    using VSA.EXASOL_ADAPTER WITH
    CONNECTION_NAME = 'LOCAL_BOB'
    -- no SCHEMA_NAME filter !
;
```

#### Bug 1: Metadata for tables with same name is just mashed together
```sql
describe nomercy.FOR_BOB;
```
results in
```text
COLUMN_NAME SQL_TYPE
----------- ------------- 
I           DECIMAL(18,0) 
J           DECIMAL(18,0) 
```

#### Bug 2: Generated SQL is not schema-qualified
```sql
select * from nomercy.FOR_BOB;
```
results in
```text
ETL-5402: JDBC-Client-Error: Failed to initialize Query: object "FOR_BOB" not found
```
because:
```sql
explain virtual select i from nomercy.FOR_BOB;
-- IMPORT INTO (c1 DECIMAL(18, 0)) FROM JDBC AT LOCAL_BOB STATEMENT 'SELECT "FOR_BOB"."I" FROM "FOR_BOB"'
```

### PR DESCRIPTION
**Pull request by ckunki**
fixes #92

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/exasol/MandatoryProperty.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+import com.exasol.adapter.properties.PropertyValidationException;
+import com.exasol.adapter.properties.PropertyValidator;
+import com.exasol.errorreporting.ExaError;
+
+/**
+ * {@link PropertyValidator} for validation of a mandatory property.
+ */
+public class MandatoryProperty implements PropertyValidator {
+    /**
+     *
```
Comment (kaklakariada) [inline src/main/java/com/exasol/adapter/dialects/exasol/MandatoryProperty.java:13]:
```suggestion
     * Create a new validator.
     *
```

File: src/main/java/com/exasol/adapter/dialects/exasol/MandatoryProperty.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+        this.dialect = dialect;
+        this.element = element;
+        this.property = property;
+    }
+
+    @Override
+    public void validate(final AdapterProperties properties) throws PropertyValidationException {
+        if (!properties.hasSchemaName()) {
+            throw new PropertyValidationException(ExaError.messageBuilder("E-VSEXA-6")
+                    .message("{{dialect|uq}} virtual schema dialect requires to specify a {{element1|uq}}.",
```
Comment (kaklakariada) [inline src/main/java/com/exasol/adapter/dialects/exasol/MandatoryProperty.java:37]: Do you need to specify the dialect as argument? This will always be the Exasol VS in this repo.

File: src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectTest.java [hunk 3]
```diff
@@ -171,28 +173,25 @@ void testCreateFromExaQueryRewriter(@Mock final Connection connectionMock) throw
...
     @Test
     void checkValidBoolOptionsWithExaConnection() throws PropertyValidationException {
-        setMandatoryProperties();
-        this.rawProperties.put(EXASOL_IMPORT_PROPERTY, "TrUe");
-        this.rawProperties.put(EXASOL_CONNECTION_PROPERTY, "MY_EXA_CONNECTION");
-        final AdapterProperties adapterProperties = new AdapterProperties(this.rawProperties);
+        final AdapterProperties adapterProperties = mandatory() //
+                .with(EXASOL_IMPORT_PROPERTY, "TrUe") //
+                .with(EXASOL_CONNECTION_PROPERTY, "MY_EXA_CONNECTION") //
+                .build();
```
Comment (kaklakariada) [inline src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectTest.java:179]: 👍

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — APPROVED** [review]
