### PR TITLE
#49: Fixed double literal rendering

### LINKED ISSUE #49: Render doubles with E notation
Currently, doubles are rendered java doubles but they should be rendered in the notation with an E.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #49

### CODE REVIEW

File: src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitorTest.java [hunk 1]
```diff
@@ -44,6 +44,6 @@ void testVisitSqlLiteralTimestampUtc() {
     void testVisitSqlLiteralDouble() {
         final ExasolSqlGenerationVisitor exasolSqlGenerationVisitor = new ExasolSqlGenerationVisitor(
                 this.exasolSqlDialect, null);
-        assertThat(exasolSqlGenerationVisitor.visit(new SqlLiteralDouble(1.23)), equalTo("CAST(1.23 AS DOUBLE)"));
+        assertThat(exasolSqlGenerationVisitor.visit(new SqlLiteralDouble(1.23)), equalTo("CAST(1.23E0 AS DOUBLE)"));
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitorTest.java:47]: From reading #49, is it only requires exponent with zero `E0`? I think, the sql visitor is already going to generate correct exponentiation, right?

**Review by morazow — APPROVED** [review]

File: src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitorTest.java (hunk 1 above)
Comment (jakobbraun) [reply src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlGenerationVisitorTest.java:47]: yes
